---
_role: &_role
  stage: "Roles Testing"
  language: python
  dist: bionic
  python: "3.7"
  services:
    - docker
  cache: pip
  install:
    - pip install molecule docker pytest
  script:
    - molecule --version
    - ansible --version
    - cd "$TRAVIS_JOB_NAME" && molecule test

jobs:
  include:
    - <<: *_role
      name: base.profile
    - <<: *_role
      name: base.security
    - <<: *_role
      name: base.docker
    - <<: *_role
      name: docker.ouroboros
