---
language: python
python:
  - "2.7"
  - "3.6"
services:
  - docker
install:
  - pip install molecule docker pytest
script:
  - molecule --version
  - ansible --version
  - cd base && molecule test
