---
- name: "Set up server utils and users"
  include_vars: core.yml

- name: "Update system"
  apt:
    update_cache: true
    upgrade: dist

- name: "Install specified packages"
  apt:
    name: "{{ packages }}"

- name: "Create user(s): {{ users|join(', ') }}"
  user:
    name: "{{ item }}"
    shell: /usr/bin/zsh
    groups:
      - sudo
    append: yes
    state: present
  with_items: "{{ users }}"
