---
- name: "Set up server security"
  include_vars: security.yml

- name: "Install Fail2Ban"
  apt:
    name: fail2ban

- name: "Configure Fail2Ban"
  copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
  notify:
    - enable fail2ban

- name: "Set up SSHD"
  blockinfile:
    dest: /etc/ssh/sshd_config
    backup: true
    block: |
      PasswordAuthentication no
      PermitEmptyPasswords no
      PermitRootLogin no
      PermitUserEnvironment yes
      PubkeyAuthentication yes
  notify: restart sshd

- name: "Set up Linux Hardening config"
  copy:
    src: sysctl.conf
    dest: /etc/sysctl.conf
    owner: root
    group: root
  notify: reload sysctl

- name: "Copy Firewall script"
  template:
    src: firewall.j2
    dest: /etc/firewall
    owner: root
    group: root
    mode: 0744

- name: "Copy firewall systemd unit file"
  copy:
    src: firewall.unit
    dest: /etc/systemd/system/firewall.service
    owner: root
    group: root
    mode: 0644
  notify: enable firewall
