---
- name: "Set up ZSH shell (with Oh My ZSH)"
  include_vars: shell.yml

- name: "Install oh_my_zsh for root"
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: /root/.oh-my-zsh
    version: master
  register: cloning
  when:
    - config_root is defined
    - config_root

- name: "Install custom ZSH theme for root"
  git:
    repo: "{{ custom_theme_repo }}"
    dest: /root/.oh-my-zsh/custom/themes/{{ theme }}
    version: master
  register: cloning
  when:
    - config_root is defined
    - config_root
    - custom_theme_repo is defined

- name: "Link ZSH theme file to custom theme directory for root"
  file:
    src: /root/.oh-my-zsh/custom/themes/{{ theme }}/{{ theme }}.zsh-theme
    dest: /root/.oh-my-zsh/custom/themes/{{ theme }}.zsh-theme
    state: link
  when:
    - config_root is defined
    - config_root
    - custom_theme_repo is defined

- name: "Upload custom zshrc for root"
  template:
    src: zshrc.j2
    dest: /root/.zshrc
    owner: root
    group: root
    mode: 0644
  when:
    - config_root is defined
    - config_root

- name: "Install oh_my_zsh for user(s): {{ users|join(', ') }}"
  become: true
  become_user: "{{ item }}"
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: /home/{{ item }}/.oh-my-zsh
    version: master
  register: cloning
  with_items: "{{ users }}"

- name: "Install custom ZSH theme for user(s): {{ users|join(', ') }}"
  become: true
  become_user: "{{ item }}"
  git:
    repo: "{{ custom_theme_repo }}"
    dest: /home/{{ item }}/.oh-my-zsh/custom/themes/{{ theme }}
    version: master
  register: cloning
  with_items: "{{ users }}"
  when: custom_theme_repo is defined

- name: "Link ZSH theme to theme directory for user(s): {{ users|join(', ') }}"
  become: true
  become_user: "{{ item }}"
  file:
    src: /home/{{ item }}/.oh-my-zsh/custom/themes/{{ theme }}/{{ theme }}.zsh-theme
    dest: /home/{{ item }}/.oh-my-zsh/custom/themes/{{ theme }}.zsh-theme
    state: link
  with_items: "{{ users }}"
  when: custom_theme_repo is defined

- name: "Upload custom zshrc for user(s): {{ users|join(', ') }}"
  become: true
  become_user: "{{ item }}"
  template:
    src: zshrc.j2
    dest: /home/{{ item }}/.zshrc
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0644
  with_items: "{{ users }}"
